import React from 'react'

const CopyRight = () => {
    window.scrollTo(0, 0)
    return (
        <div className="container mt-5">
            <h6 className="topic-heading mb-3">
                Proshop Terms of Use
            </h6>
            <h6 className="topic-heading mb-3">
                This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </h6>
            <h6 className="topic-heading mb-3">
                This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name [www.Proshop.com][www.Proshop.com] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”)
            </h6>
            <p>
                The Platform is owned by Proshop Internet Private Limited a company incorporated under the Companies Act, 1956 with its registered office at Proshop Pharma and Warehouse near Noida Golf Course, Sector 38, Delhi NCR, India - 201303 (hereinafter referred to as "Proshop").
            </p>
            <p>
                Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Proshop Internet Private Limited and these terms and conditions including the policies constitute Your binding obligations, with Proshop.
            </p>
            <p>
                For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Proshop allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Proshop Internet Private Limited.
            </p>
            <p>
                When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform.
            </p>
            <h6 className="topic-heading mb-3">
                ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
            </h6>
            <p>
                By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Proshop Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.
            </p>
            <h6 className="topic-heading mb-3">
                Membership Eligibility
            </h6>
            <p>
                Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/ permission of a parent ormlegal guardian.
            </p>
            <p>
                As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Proshop reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to Proshop's notice or if it is discovered that You are under the age of 18 years and transacting on the Platform.
            </p>
            <h6 className="topic-heading mb-3">
                Your Account and Registration Obligations
            </h6>
            <p>
                If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.
            </p>
            <p>
                Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through a onetime password verification.
            </p>
            <p>
                You agree that Proshop shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.
            </p>
            <p>
                If You share or allow others to have access to Your account on the Platform (“Account”), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences therefrom.
            </p>
            <h6 className="topic-heading mb-3">
                Communications
            </h6>
            <p>
                When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.
            </p>
            <h6 className="topic-heading mb-3">
                Use of the Platform
            </h6>
            <p>You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles:</p>
            <ul style={{ marginLeft: "15px" }}>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    You shall not host, display, upload, modify, publish, transmit, update or share any information which:
                </li>
            </ul>
            <p>(a) belongs to another person and to which You does not have any right to;</p>
            <p>
                (b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;
            </p>
            <p>
                (c) is misleading in any way;
            </p>
            <p>
                (d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;
            </p>
            <p>
                (e) harasses or advocates harassment of another person;
            </p>
            <p>
                (f) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";
            </p>
            <p>
                (g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;
            </p>
            <p>
                (h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];
            </p>
            <p>
                (i) promotes an illegal or unauthorized copy of another person's copyrighted work (see "Copyright complaint" below for instructions on how to lodge a complaint about uploaded copyrighted material), such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;
            </p>
            <p>
                (j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);
            </p>
            <p>
                (k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;
            </p>
            <p>
                (l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;
            </p>
            <p>
                (m) contains video, photographs, or images of another person (with a minor or an adult).
            </p>
            <p>
                (n) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;
            </p>
            <p>
                (o) engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products related to the Platform. Throughout this Terms of Use, Proshop's prior written consent means a communication coming from Proshop's Legal Department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization;
            </p>
            <p>
                (p) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;
            </p>
            <p>
                (q) interferes with another USER's use and enjoyment of the Platform or any other individual's User and enjoyment of similar services;
            </p>
            <p>
                (r) refers to any Platform or URL that, in Our sole discretion, contains material that is inappropriate for the Platform or any other Platform, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.
            </p>
            <p>
                (s) harm minors in any way;
            </p>
            <p>
                (t) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;
            </p>
            <p>
                (u) violates any law for the time being in force;
            </p>
            <p>
                (v) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;
            </p>
            <p>
                (w) impersonate another person;
            </p>
            <p>
                (x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;
            </p>
            <p>
                (y) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.
            </p>
            <p>
                (z) shall not be false, inaccurate or misleading;
            </p>
            <h6 className="topic-heading mb-3">
                Privacy
            </h6>
            <p>
                We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under.Our current Privacy Policy is available at Privacy. Our current Privacy Policy is available at Privacy. f You object to Your Information being transferred or used in this way please do not use Platform. If You object to Your Information being transferred or used in this way please do not use Platform.
            </p>
            <p>
                We may share personal information with our other corporate entities and affiliates. These entities and affiliatesmay market to you as a result of such sharing unless you explicitly opt-out.
            </p>
            <p>
                We may disclose personal information to third parties. This disclosure may be required for us to provide youaccess to our Services, to comply with our legal obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our Services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.
            </p>
            <p>
                We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.
            </p>
            <p>
                We and our affiliates will share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information.
            </p>
            <h6 className="topic-heading mb-3">
                Selling
            </h6>
            <p>
                As a registered seller, you are allowed to list item(s) for sale on the Platform in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on our Platform. You must ensure that the listed items do not infringe upon the intellectual property, trade secret or other proprietary rights or rights of publicity or privacy rights of third parties. Listings may only include text descriptions, graphics and pictures that describe your item for sale. All listed items must be listed in an appropriate category on the Platform. All listed items must be kept in stock for successful fulfilment of sales.
            </p>
            <p>
                The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You agree not to list a single product in multiple quantities across various categories on the Platform. Proshop reserves the right to delete such multiple listings of the same product listed by you in various categories.
            </p>
            <h6 className="topic-heading mb-3">
                Returns Policy
            </h6>
            <p>Definition: 'Return' is defined as the action of giving back the item purchased by the Buyer to the Seller on the Proshop Platform. Following situations may arise:</p>
            <ul style={{ marginLeft: "15px" }}>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Item was defective
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Item was damaged during the Shipping
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Products was / were missing
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Wrong item was sent by the Seller.
                </li>
            </ul>
            <table style={{ border: "1px solid #000", textAlign: "center", marginBottom: "10px" }} className="policy-table">
                <tr>
                    <th>Category</th>
                    <th>Condition</th>
                </tr>
                <tr>
                    <td>Product</td>
                    <td>Should be "New" and returned with original packaging</td>
                </tr>
            </table>
            <h6 className="topic-heading mb-3">
                Payment
            </h6>
            <p>
                While availing any of the payment method/s available on the Platform, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:
            </p>
            <ul style={{ marginLeft: "15px" }}>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Lack of authorization for any transaction/s, or
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Exceeding the preset limit mutually agreed by You and between "Bank/s", or
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Any payment issues arising out of the transaction, or
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Decline of transaction for any other reason/s
                </li>
            </ul>
            <p>
                Trademark-listing description infringement
            </p>
            <ul style={{ marginLeft: "15px" }}>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Listing(s) has unlawful comparison to trademark owner's brand or product
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Listing(s) contains unlawful use of trademark owner's logo
                </li>
            </ul>
            <p>
                Copyright-item infringement
            </p>
            <ul style={{ marginLeft: "15px" }}>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Software is being offered without any license or in violation of a license
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Item(s) is unlawful duplication of printed material
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Item(s) is an unlawful copy of other copyrighted work (paintings, sculptures, etc.)
                </li>
            </ul>
            <p>
                Copyright-listing content infringement
            </p>
            <ul style={{ marginLeft: "15px" }}>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Listing(s) comprises unauthorized copy of copyrighted text
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Listing(s) comprises unauthorized copy of copyrighted image
                </li>
                <li style={{ color: "black", listStyleType: "disc" }}>
                    Listing(s) comprises unauthorized copy of copyrighted image and text
                </li>
            </ul>
            <h6 className="topic-heading mb-3">
                Contacting the Seller
            </h6>
            <p>
                At Proshop we are committed towards ensuring that disputes between sellers and buyers are settled amicably by way of the above dispute resolution mechanisms and procedures. However, in the event that a buyer wishes to contact the seller, he/ she may proceed to do so by accessing the seller related information made available by the sellers on their product listing pages. Alternatively, the buyers may also reach out to customer support at + 0261 2566788
            </p>
        </div>
    )
}

export default CopyRight
